apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-jrji
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoupuicluster/rorai-tenant/my-app/devfile-sample-jrji@sha256:8c5d3292d783756b09840ac87db248d9e9447fd70038e986045bd9ac0420e708
        name: my-nodejs
        resources: {}
status: {}
