apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-7knz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-7knz
    app.kubernetes.io/part-of: my-app
  name: devfile-sample-7knz
  namespace: rorai-tenant
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-7knz
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-7knz
    spec:
      containers:
      - image: quay.io/stonesoupuicluster/rorai-tenant/my-app/devfile-sample-7knz@sha256:7128eb9b50f61a1081cbb333d1f93eee1eba6870e0cad427509c80fe474c8e6c
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
