apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-code-with-quarkus-oqs8
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-code-with-quarkus-oqs8
    app.kubernetes.io/part-of: my-app
  name: devfile-sample-code-with-quarkus-oqs8
  namespace: rorai-tenant
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: devfile-sample-code-with-quarkus-oqs8
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: devfile-sample-code-with-quarkus-oqs8
    spec:
      containers:
      - image: quay.io/stonesoupuicluster/rorai-tenant/my-app/devfile-sample-code-with-quarkus-oqs8@sha256:4fb8c0d78b190a54e27de5fe9765b6c05274dfbbb3326935b08519e0574f07bd
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 250Mi
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
